# Generated by Django 2.0.4 on 2018-04-20 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssForHR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingsView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'AssForHR_buildings_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreaLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaid', models.CharField(max_length=40, unique=True)),
                ('area_name', models.CharField(max_length=200)),
                ('loc_x', models.IntegerField(default=0)),
                ('loc_y', models.IntegerField(default=0)),
                ('loc_z', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='building_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_model_id', models.CharField(default='0', max_length=40, unique=True)),
                ('building_model_name', models.CharField(default='undifined2', max_length=200)),
                ('building_type', models.CharField(max_length=40)),
                ('building_descr', models.TextField()),
                ('building_path', models.CharField(max_length=400)),
                ('work_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('max_worker_num', models.IntegerField(default=0)),
                ('product_type', models.CharField(max_length=40)),
                ('production_num', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuildingID', models.CharField(default='0', max_length=40)),
                ('OwnerID', models.CharField(default='undifined', max_length=200)),
                ('BuildingStatusID', models.CharField(default='undifined', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerID', models.CharField(default='0', max_length=40, unique=True)),
                ('Name', models.CharField(default='undifined', max_length=200)),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='public_config_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(default='0_0', max_length=40)),
                ('item_name', models.CharField(default='undifined', max_length=200)),
                ('item_value', models.CharField(default='undifined', max_length=200)),
                ('order_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='public_config_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(default='0_0', max_length=40, unique=True)),
                ('group_name', models.CharField(default='undifined', max_length=200)),
                ('order_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='starlists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starid', models.CharField(max_length=40, unique=True)),
                ('star_name', models.CharField(max_length=200)),
                ('loc_x', models.IntegerField(default=0)),
                ('loc_y', models.IntegerField(default=0)),
                ('loc_z', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='public_config_code',
            name='group_id',
            field=models.ForeignKey(default='0_0', on_delete=django.db.models.deletion.CASCADE, to='AssForHR.public_config_group', to_field='group_id'),
        ),
        migrations.AddField(
            model_name='buildinglists',
            name='PlayerID',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='AssForHR.PlayerLists', to_field='PlayerID'),
        ),
        migrations.AddField(
            model_name='buildinglists',
            name='areaid',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='AssForHR.AreaLists', to_field='areaid'),
        ),
        migrations.AddField(
            model_name='buildinglists',
            name='building_model_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='AssForHR.building_model', to_field='building_model_id'),
        ),
        migrations.AddField(
            model_name='arealists',
            name='loc_star',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='AssForHR.starlists', to_field='starid'),
        ),
    ]
