# Generated by Django 2.0.4 on 2018-04-15 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssForHR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingsView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'AssForHR_buildings_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreaLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaid', models.CharField(max_length=40, unique=True)),
                ('area_name', models.CharField(max_length=200)),
                ('loc_x', models.IntegerField(default=0)),
                ('loc_y', models.IntegerField(default=0)),
                ('loc_z', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Building_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingID', models.CharField(max_length=40)),
                ('buildingName', models.CharField(default='undifined2', max_length=200)),
                ('buildingType', models.CharField(max_length=40)),
                ('buildingDescr', models.TextField()),
                ('buildingPath', models.CharField(max_length=400)),
                ('workHours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('maxWorkerNum', models.IntegerField(default=0)),
                ('productType', models.CharField(max_length=40)),
                ('productionNum', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuildingID', models.CharField(default='0', max_length=40)),
                ('OwnerID', models.CharField(default='undifined', max_length=200)),
                ('BuildingStatusID', models.CharField(default='undifined', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerID', models.CharField(default='0', max_length=40, unique=True)),
                ('Name', models.CharField(default='undifined', max_length=200)),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicConfigCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemID', models.CharField(default='0_0', max_length=40)),
                ('ItemName', models.CharField(default='undifined', max_length=200)),
                ('ItemValue', models.CharField(default='undifined', max_length=200)),
                ('OrderID', models.IntegerField(default=0)),
                ('GroupID', models.CharField(default='0_0', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PublicConfigGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupID', models.CharField(default='0_0', max_length=40)),
                ('GroupName', models.CharField(default='undifined', max_length=200)),
                ('OrderID', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='starlists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starid', models.CharField(max_length=40, unique=True)),
                ('star_name', models.CharField(max_length=200)),
                ('loc_x', models.IntegerField(default=0)),
                ('loc_y', models.IntegerField(default=0)),
                ('loc_z', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='buildinglists',
            name='PlayerID',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='AssForHR.PlayerLists', to_field='PlayerID'),
        ),
        migrations.AddField(
            model_name='buildinglists',
            name='areaid',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='AssForHR.AreaLists', to_field='areaid'),
        ),
        migrations.AddField(
            model_name='arealists',
            name='loc_star',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='AssForHR.starlists', to_field='starid'),
        ),
    ]
