# Generated by Django 2.0.4 on 2018-04-20 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssForHR', '0002_auto_20180420_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildinglists',
            old_name='BuildingStatusID',
            new_name='building_status_id',
        ),
        migrations.AlterField(
            model_name='public_config_code',
            name='group_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='AssForHR.public_config_group', to_field='group_id'),
        ),
        migrations.AlterField(
            model_name='public_config_group',
            name='group_id',
            field=models.CharField(default='0', max_length=40, unique=True),
        ),
    ]
