# Generated by Django 2.0.4 on 2018-04-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssForHR', '0003_auto_20180420_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building_model',
            old_name='building_descr',
            new_name='building_desc',
        ),
    ]
