# Generated by Django 2.0.4 on 2018-04-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssForHR', '0004_auto_20180420_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildinglists',
            name='now_production_num',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buildinglists',
            name='now_worker_num',
            field=models.IntegerField(default=0),
        ),
    ]
