# Generated by Django 2.0.4 on 2018-04-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssForHR', '0005_auto_20180420_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildinglists',
            name='now_work_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
