# Generated by Django 2.0.4 on 2018-04-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssForHR', '0006_buildinglists_now_work_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='check_recode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'checkout_rcd',
            },
        ),
    ]
