# Generated by Django 2.0.4 on 2018-04-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssForHR', '0007_check_recode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='check_recode',
            table='check_record_view',
        ),
    ]
