# Generated by Django 2.0.4 on 2018-04-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssForHR', '0008_auto_20180424_1643'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='check_recode',
            table='check_record',
        ),
    ]
