# Generated by Django 2.0.4 on 2018-04-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssForHR', '0009_auto_20180424_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='check_out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default=' ', max_length=40)),
                ('emplid', models.CharField(default=' ', max_length=40)),
                ('name', models.CharField(default=' ', max_length=40)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('check_time', models.DateTimeField()),
                ('machineid', models.CharField(default=' ', max_length=40)),
            ],
        ),
    ]
