# Generated by Django 2.0.4 on 2018-04-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssForHR', '0010_check_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='system_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=40)),
            ],
        ),
    ]
